namespace :mobile do

  desc "Generates a javascript file of all the different sports' athletic attributes"
  task :regenerate_athletic_attributes => :environment do

    hash = {}

    Recruit # Force load the recruit base class before trying to load rest
    Dir['app/models/sport/*'].each do |f|
      name = f.gsub(/app\/models\/([^.]+)\.rb/, '\\1')
      cls = name.camelize.constantize
      if cls.respond_to?(:athletic_attributes)
        hash[cls.to_s] = cls.athletic_attributes
      end
    end

    file_data = <<EOJ
// This file is automatically generated by
// rake mobile:regenerate_athletic_attributes

Person.athleticAttributes = #{hash.to_json}
EOJ

    puts file_data

  end

end
