require 'acceptance/acceptance_helper'

feature "Alerts", %q{
  In order to track my compliance violations
  As a compliance officer
  I want to recieve and manage alerts generated by my coaches
} do

  background do
    account = Fabricate(:full_account)
    program = Fabricate(:program, account: account)

    log_in(program: program)
  end

  scenario "Viewing a recruit without a graduation year" do
    recruit = Fabricate(:baseball_recruit, :program => @program, :graduation_year => '')

    visit person_path(recruit)

    within('.interaction-status') do
      page.should have_content("graduation")
    end
  end

  scenario "Placing a call when violating a rule", js: true do
    recruit = Fabricate(:baseball_recruit, :program => @program, :graduation_year => '2012')

    visit person_path(recruit)

    within('.interaction-status') do
      page.should have_content("cannot place a call")
    end

    click_link 'Phone call'

    within('.interaction-form.new.phone-call') do
      fill_in 'Text', :with => 'Test Notes'
      fill_in 'Phone number', :with => '7345551212'
      fill_in 'Duration', :with => '1:20:05'
      select 'Completed', :from => 'Status'

      click_button 'Save'
    end

    within('ul.interactions') do
      page.should have_content("Alert")
      page.should have_content("Exceeded")
    end

    within('.interaction-status') do
      page.should have_content('determine if you may call')
    end
  end

  scenario "placing a call without violating a rule", js: true do
    Timecop.travel(2011, 01, 15, 0, 0, 0) do
      recruit = Fabricate(:baseball_recruit, :program => @program, :graduation_year => '2012')
      Fabricate(
        :january_phone_call_rule,
        program: @program,
        calls_allowed: 1,
        school_class: 'Junior'
      )

      visit person_path(recruit)

      within('.interaction-status') do
        page.should have_content("may place 1 call")
      end

      click_link 'Phone call'

      within('.interaction-form.new.phone-call') do
        fill_in 'Text', :with => 'Test Notes'
        fill_in 'Phone number', :with => '7345551212'
        fill_in 'Duration', :with => '1:20:05'
        fill_in 'Interaction time', :with => "2011-01-15"
        select 'Completed', :from => 'Status'

        click_button 'Save'
      end

      within('ul.interactions') do
        page.should have_content("Phone Call")
        page.should have_no_content("Alert")
      end

      within('.interaction-status') do
        page.should have_content('determine if you may call')
      end
    end
  end
end
